opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_general_examination.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_mother_observation.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_mother_well_being.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_admission_information.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_triage.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_general_examination_relevance.yml, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_mother_observation_relevance.yml, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_mother_wellbeing_relevance.yml, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_triage_relevance.yml
1. [Update Reasons for referral/management received](https://github.com/SoftmedTanzania/opensrp-client-chw-hf/issues/252)
2. [Add Reason for Admission in Admission Information](https://github.com/SoftmedTanzania/opensrp-client-chw-hf/issues/253)
=> Add Reason for Admission in Admission Information

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_general_examination.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_mother_observation.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_mother_well_being.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_admission_information.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_current_labour.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_triage.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_general_examination_relevance.yml, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_mother_observation_relevance.yml, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_mother_wellbeing_relevance.yml, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_triage_relevance.yml, opensrp-chw-hf/src/main/res/values/strings.xml
=> Refactor Current labor title changes to "Current Labor History"

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_anc_clinic_findings.json
=> :hammer: added unknown hiv status option in ld anc_clinic findings

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_current_labour.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_triage.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_true_labour_confirmation.json, opensrp-chw-hf/src/main/assets/rule/labor_and_delivery_registration_current_labor_relevance.yml
closes #265, closes #259, closes #258
=> :recycle: Fetal movement status, true labor confirmation update

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_admission_information.json
=> :hammer: added danger signs and risk factors to admission information

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_placenta_and_membrane.json
=> Update: New fields added in active management of 3rd stage of labor

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_vaginal_examination.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_vaginal_examination_relevance.yml
=> Update : vaginal Examination Action

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_general_examination.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_general_examination_relevance.yml
=> Update : General Examination Action

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_mode_of_delivery.json, opensrp-chw-hf/src/main/assets/json.form/sub_form/labour_and_delivery_registration_past_obstetric_history_sub_form.json
=> Update mode delivery

opensrp-chw-hf/build.gradle
=> bump: version code

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_mode_of_delivery.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_mode_of_delivery_relevance.yml
Closes [323](https://github.com/SoftmedTanzania/opensrp-client-chw-hf/issues/323)
=> :construction: Caeserean option for delivery method stage

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_obstetric_history.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_registration_obstetric_history_calculation.yml
Closes [324](https://github.com/SoftmedTanzania/opensrp-client-chw-hf/issues/324)
=> Constraint Para plus number of abortions not exceeding Gravida

opensrp-chw-hf/build.gradle, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_labour_progress.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_mother_well_being.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_labour_progress_relevance.yml, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/actionhelper/LDPartographLabourProgressActionHelper.java, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/activity/ReferralRegistrationActivity.java, opensrp-chw-hf/src/main/res/values/strings.xml
=> 312 progress of labor update

opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/actionhelper/LDGeneralExaminationActionHelper.java
=> :hammer: refactored ld general examination action helper

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_vaginal_examination.json, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/actionhelper/LDVaginalExaminationActionHelper.java
=> :hammer: refactored vaginal examination

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_placenta_and_membrane.json
=> :hammer: refactored ld expulsion of placenta and membranes

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_mother_observation.json
=> Update mother observation action

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_current_labour.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_registration_current_labour_calculation.yml, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_registration_current_labour_relevance.yml
=> :hammer: added prompts for prom

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_maternal_complications.json, opensrp-chw-hf/src/main/assets/json.form/sub_form/labour_and_delivery_registration_past_obstetric_history_sub_form.json
=> Fix issue 331

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_maternal_complications.json, opensrp-chw-hf/src/main/assets/json.form/sub_form/labour_and_delivery_registration_past_obstetric_history_sub_form.json, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/interactor/LDPostDeliveryManagementMotherActivityInteractor.java, opensrp-chw-hf/src/main/res/values/strings.xml
=> Restart ld issue 331, and Fix issue 436

opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/activity/LDPostDeliveryManagementMotherActivity.java, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/interactor/LDPostDeliveryManagementMotherActivityInteractor.java
Closes [435](https://github.com/SoftmedTanzania/opensrp-client-chw-hf/issues/435)
=> :bug: Fixes for actionList list refreshing

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_vaginal_examination.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_vaginal_examination_calculation.yml, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_vaginal_examination_relevance.yml, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/interactor/LDVisitInteractor.java, opensrp-chw-hf/src/main/res/values-sw/strings.xml, opensrp-chw-hf/src/main/res/values/strings.xml
=> ♻️ Update vaginal examination

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_stage4_newborn.json, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/activity/LDPostDeliveryManagementMotherActivity.java, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/interactor/LDPostDeliveryManagementMotherActivityInteractor.java, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/utils/LDVisitUtils.java
Closes [#424 ](https://github.com/SoftmedTanzania/opensrp-client-chw-hf/issues/424)
=> :zap: Make newborn registration at stage 4 editable

opensrp-chw-hf/build.gradle, opensrp-chw-hf/src/main/assets/ec_client_fields.json, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/actionhelper/LDVaginalExaminationActionHelper.java, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/utils/Constants.java
=> Update vaginal examination

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_mother_well_being.json
=> ♻️  Add required pulse rate

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_placenta_and_membrane.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_anc_clinic_findings.json, opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_true_labour_confirmation.json, opensrp-chw-hf/src/main/assets/rule/labour_and_delivery_triage_relevance.yml
Closes #299, and fixes other form related issues
=> Fixing form issues for ld

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_stage4_family_planning.json, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/actionhelper/PostDeliveryFamilyPlanningActionHelper.java, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/interactor/LDPostDeliveryManagementMotherActivityInteractor.java, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/utils/Constants.java, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/utils/LDVisitUtils.java, opensrp-chw-hf/src/main/res/values/strings.xml
=> :zap: Add Family Planning Action in Stage 4

opensrp-chw-hf/src/main/assets/rule/labor_and_delivery_registration_current_labor_relevance.yml, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/actionhelper/LDRegistrationTrueLabourConfirmationAction.java, opensrp-chw-hf/src/main/res/values/strings.xml
=> Fix ld issue 462

opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_triage.json, opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/actionhelper/LDRegistrationTriageAction.java
=> Fix ld issue 485
